"Method","Name","Error","Occurrences"
"PUT","/qa/answer/1/report","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/answer/1/report (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc54030a670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",2096
"PUT","/qa/answer/1/report","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/answer/1/report (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5605f2400>: Failed to establish a new connection: [Errno 24] Too many open files'))",197
"PUT","/qa/question/10000/helpful","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/question/10000/helpful (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc59064cca0>: Failed to establish a new connection: [Errno 24] Too many open files'))",213
"GET","/qa/1000/answers","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/1000/answers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc54030a4f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",2103
"PUT","/qa/answer/1/helpful","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/answer/1/helpful (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5302ceb50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",2053
"PUT","/qa/question/10000/report","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/question/10000/report (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5302e6d00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",2172
"GET","/qa/1000/answers","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/1000/answers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc55087ffa0>: Failed to establish a new connection: [Errno 24] Too many open files'))",193
"GET","/qa/1000","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/1000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5906b6ca0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",9771
"PUT","/qa/answer/1/helpful","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/answer/1/helpful (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5302cea30>: Failed to establish a new connection: [Errno 24] Too many open files'))",194
"POST","/qa","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5302e6d60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",2218
"POST","/qa/1000/answers","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/1000/answers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc53030d2e0>: Failed to establish a new connection: [Errno 24] Too many open files'))",195
"GET","/qa/1000/answers","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",444
"POST","/qa","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc520371040>: Failed to establish a new connection: [Errno 24] Too many open files'))",177
"PUT","/qa/question/10000/helpful","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/question/10000/helpful (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc53030d6a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",2144
"POST","/qa/1000/answers","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",427
"POST","/qa","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",462
"PUT","/qa/answer/1/report","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",418
"PUT","/qa/question/10000/report","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/question/10000/report (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc560609af0>: Failed to establish a new connection: [Errno 24] Too many open files'))",168
"PUT","/qa/answer/1/helpful","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",418
"GET","/qa/1000","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/1000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc530322100>: Failed to establish a new connection: [Errno 24] Too many open files'))",849
"POST","/qa/1000/answers","HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /qa/1000/answers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc5302e6460>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",2040
"PUT","/qa/question/10000/helpful","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",391
"PUT","/qa/question/10000/report","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",396
"GET","/qa/1000","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",2078